/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	theme: {
		extend: {
			colors: {
				"on-tertiary-fixed": "#2c4655",
				"surface-container-highest": "#e2e2e3",
				"on-tertiary-fixed-variant": "#486272",
				"surface-container-low": "#f5f3f3",
				"on-surface": "#303333",
				"on-primary-container": "#4a5355",
				"surface-dim": "#d9dada",
				"on-background": "#303333",
				"surface-tint": "#576062",
				"tertiary-fixed-dim": "#c2def0",
				outline: "#797b7b",
				"on-surface-variant": "#5d5f60",
				"surface-container-lowest": "#ffffff",
				error: "#9f403d",
				surface: "#fbf9f8",
				"tertiary-fixed": "#d0ecff",
				"inverse-surface": "#0e0e0e",
				"on-error": "#fff7f6",
				"surface-bright": "#fbf9f8",
				"surface-container": "#eeeeed",
				"surface-variant": "#e2e2e3",
				secondary: "#5c6060",
				"secondary-fixed-dim": "#d2d5d5",
				"inverse-on-surface": "#9e9d9c",
				"tertiary-container": "#d0ecff",
				"on-secondary": "#f7f9fa",
				"on-primary-fixed": "#384143",
				"secondary-fixed": "#e1e3e3",
				background: "#fbf9f8",
				"on-error-container": "#752121",
				"primary-container": "#dbe4e6",
				"secondary-dim": "#505454",
				"primary-fixed-dim": "#ccd6d8",
				"on-primary-fixed-variant": "#545d5f",
				"on-secondary-container": "#4f5253",
				"secondary-container": "#e1e3e3",
				"on-primary": "#f0f9fb",
				"on-secondary-fixed": "#3c4040",
				"inverse-primary": "#e6f0f1",
				tertiary: "#486272",
				"on-tertiary-container": "#3e5868",
				"error-dim": "#4e0309",
				"outline-variant": "#b1b2b2",
				primary: "#576062",
				"primary-fixed": "#dbe4e6",
				"primary-dim": "#4b5456",
				"tertiary-dim": "#3c5666",
				"error-container": "#fe8983",
				"on-tertiary": "#f4faff",
				"on-secondary-fixed-variant": "#595c5d",
				"surface-container-high": "#e8e8e8",
			},
			borderRadius: {
				DEFAULT: "0px",
				lg: "0px",
				xl: "0px",
				full: "9999px",
			},
			fontFamily: {
				headline: ["Manrope", "sans-serif"],
				body: ["Inter", "sans-serif"],
				label: ["Inter", "sans-serif"],
			},
		},
	},
	plugins: [require("@tailwindcss/forms")],
};
